// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import Image from './Image';
import Repeater from './Repeater';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';

export {
	Hero,
	Image,
	Repeater,
	TextWithFeatures,
	TextWithImage,
};

export const components = {
	hero: Hero,
	image: Image,
	repeater: Repeater,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
};
